-- =====================================================================
-- Prophet AA Emmanuel Ministries — Supabase schema
-- Run this in Supabase → SQL Editor → New query → Run.
-- Creates: videos (drives the Messages section), contacts, donations.
-- Includes Row Level Security so the public can ONLY do what's safe.
-- =====================================================================

-- ---------- VIDEOS (Messages that play on the site) ----------
create table if not exists public.videos (
  id          bigint generated by default as identity primary key,
  title       text not null,
  category    text,                 -- shown as the small label (e.g. "Praise & Worship")
  youtube_url text not null,        -- full link, e.g. https://www.youtube.com/watch?v=XXXX
  description text,
  sort_order  int  default 0,
  published   boolean default true,
  created_at  timestamptz default now()
);

alter table public.videos enable row level security;

-- Anyone (anon) can READ published videos. Only the dashboard / service role can write.
drop policy if exists "Public can read published videos" on public.videos;
create policy "Public can read published videos"
  on public.videos for select
  using (published = true);

-- Seed a few starter videos (replace youtube_url with the Prophet's own).
insert into public.videos (title, category, youtube_url, description, sort_order) values
  ('Distance Is Not A Barrier — Just Have Faith', 'Prophetic Word', 'https://www.youtube.com/watch?v=rYJWRyg89wA', 'Wherever you are, distance is not a barrier — receive your healing and breakthrough by faith.', 1),
  ('Way Maker — Worship Encounter', 'Praise & Worship', 'https://www.youtube.com/watch?v=hWgJij1MSI4', 'Enter His presence with this powerful worship and let God move in your situation.', 2),
  ('I Know Who I Am', 'Identity in Christ', 'https://www.youtube.com/watch?v=frtZ4XfoXxM', 'Discover your true identity as a child of God — chosen, redeemed and victorious.', 3),
  ('Who Is On The Lord''s Side', 'Consecration', 'https://www.youtube.com/watch?v=aULdIMQn1AQ', 'A call to full surrender and consecration to the Lordship of Jesus Christ.', 4),
  ('TobeChukwu — Praise God', 'Thanksgiving', 'https://www.youtube.com/watch?v=0N8jWaBQUuA', 'Lift your voice in thanksgiving — He is worthy of all our praise and adoration.', 5),
  ('Way Maker (Live)', 'Live Worship', 'https://www.youtube.com/watch?v=QM8jQHE5AAk', 'A live worship experience — miracle worker, promise keeper, light in the darkness.', 6),
  ('Worship & Praise Medley', 'Worship Night', 'https://www.youtube.com/watch?v=eNKjlNyOFjY', 'An atmosphere of worship — soak in His presence and be refreshed in spirit.', 7),
  ('A Night of Praise Celebration', 'Praise', 'https://www.youtube.com/watch?v=J4vTs2py2ro', 'Celebrate the goodness of God with thanksgiving, praise and adoration.', 8)
on conflict do nothing;

-- ---------- CONTACTS (contact form submissions) ----------
create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text,
  email      text,
  subject    text,
  message    text,
  created_at timestamptz default now()
);

alter table public.contacts enable row level security;

-- The public website may INSERT a message, but cannot read others' messages.
drop policy if exists "Public can submit contact" on public.contacts;
create policy "Public can submit contact"
  on public.contacts for insert
  with check (true);

-- ---------- DONATIONS (lead capture for every give attempt) ----------
create table if not exists public.donations (
  id         bigint generated by default as identity primary key,
  name       text,
  email      text,
  phone      text,
  amount     numeric,
  status     text,
  created_at timestamptz default now()
);

alter table public.donations enable row level security;

drop policy if exists "Public can submit donation" on public.donations;
create policy "Public can submit donation"
  on public.donations for insert
  with check (true);

-- =====================================================================
-- To VIEW submitted contacts/donations: open Supabase → Table Editor
-- (you are the project owner, so the dashboard bypasses RLS).
-- To add/edit videos: use the Table Editor on the `videos` table, or
-- INSERT rows here — the website picks them up automatically.
-- =====================================================================
