-- =====================================================================
-- Prophet AA Emmanuel Ministries — Supabase schema (full / fresh setup)
-- Run in Supabase → SQL Editor → New query → Run.
-- Everything the site shows (videos, hero images) + everything it
-- collects (contacts, donations) lives here and is edited from the
-- Supabase Table Editor — no code changes needed.
-- (If you already ran the first version, use the MIGRATION script the
--  assistant gave you instead, so you don't lose data.)
-- =====================================================================

-- ---------- VIDEOS (grouped into sections on the site) ----------
create table if not exists public.videos (
  id          bigint generated by default as identity primary key,
  title       text not null,
  section     text default 'Recent Messages',  -- the heading this video appears under
  category    text,                             -- small label on the card
  youtube_url text not null,                    -- https://www.youtube.com/watch?v=XXXX
  description text,
  play_mode   text default 'inline',            -- 'inline' = play on-site | 'link' = open YouTube
  sort_order  int  default 0,                   -- controls order (and section order)
  published   boolean default true,
  created_at  timestamptz default now()
);
alter table public.videos enable row level security;
drop policy if exists "Public can read published videos" on public.videos;
create policy "Public can read published videos"
  on public.videos for select using (published = true);

insert into public.videos (title, section, category, youtube_url, description, play_mode, sort_order) values
  ('Distance Is Not A Barrier — Just Have Faith', 'Recent Messages', 'Prophetic Word', 'https://www.youtube.com/watch?v=rYJWRyg89wA', 'Wherever you are, distance is not a barrier — receive your healing and breakthrough by faith.', 'inline', 1),
  ('I Know Who I Am', 'Recent Messages', 'Identity in Christ', 'https://www.youtube.com/watch?v=frtZ4XfoXxM', 'Discover your true identity as a child of God — chosen, redeemed and victorious.', 'inline', 2),
  ('Who Is On The Lord''s Side', 'Recent Messages', 'Consecration', 'https://www.youtube.com/watch?v=aULdIMQn1AQ', 'A call to full surrender and consecration to the Lordship of Jesus Christ.', 'inline', 3),
  ('Way Maker — Worship Encounter', 'Praise & Worship', 'Worship', 'https://www.youtube.com/watch?v=hWgJij1MSI4', 'Enter His presence with this powerful worship and let God move in your situation.', 'inline', 4),
  ('TobeChukwu — Praise God', 'Praise & Worship', 'Thanksgiving', 'https://www.youtube.com/watch?v=0N8jWaBQUuA', 'Lift your voice in thanksgiving — He is worthy of all our praise and adoration.', 'inline', 5),
  ('Way Maker (Live)', 'Praise & Worship', 'Live Worship', 'https://www.youtube.com/watch?v=QM8jQHE5AAk', 'A live worship experience — miracle worker, promise keeper, light in the darkness.', 'inline', 6),
  ('Worship & Praise Medley', 'Crusades & Conferences', 'Worship Night', 'https://www.youtube.com/watch?v=eNKjlNyOFjY', 'An atmosphere of worship — soak in His presence and be refreshed in spirit.', 'link', 7),
  ('A Night of Praise Celebration', 'Crusades & Conferences', 'Praise', 'https://www.youtube.com/watch?v=J4vTs2py2ro', 'Celebrate the goodness of God with thanksgiving, praise and adoration.', 'link', 8)
on conflict do nothing;

-- ---------- HERO SLIDES (the big banner images) ----------
create table if not exists public.hero_slides (
  id         bigint generated by default as identity primary key,
  image_url  text not null,
  headline   text,
  sort_order int default 0,
  published  boolean default true,
  created_at timestamptz default now()
);
alter table public.hero_slides enable row level security;
drop policy if exists "Public can read hero slides" on public.hero_slides;
create policy "Public can read hero slides"
  on public.hero_slides for select using (published = true);

insert into public.hero_slides (image_url, sort_order) values
  ('https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=1920&q=80', 1),
  ('https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1920&q=80', 2),
  ('https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=1920&q=80', 3),
  ('https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1920&q=80', 4),
  ('https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1920&q=80', 5)
on conflict do nothing;

-- ---------- CONTACTS (contact form submissions) ----------
create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text,
  email      text,
  subject    text,
  message    text,
  created_at timestamptz default now()
);
alter table public.contacts enable row level security;
drop policy if exists "Public can submit contact" on public.contacts;
create policy "Public can submit contact"
  on public.contacts for insert with check (true);

-- ---------- DONATIONS (lead capture for every give attempt) ----------
create table if not exists public.donations (
  id         bigint generated by default as identity primary key,
  name       text,
  email      text,
  phone      text,
  amount     numeric,
  status     text,
  created_at timestamptz default now()
);
alter table public.donations enable row level security;
drop policy if exists "Public can submit donation" on public.donations;
create policy "Public can submit donation"
  on public.donations for insert with check (true);

-- =====================================================================
-- Your ADMIN DASHBOARD is Supabase → Table Editor:
--   • videos       → add/edit/remove videos & sections (site updates live)
--   • hero_slides  → change the banner images
--   • contacts / donations → view everything submitted from the site
-- =====================================================================
