-- =====================================================================
-- TESTIMONIES — migration for sites that were set up BEFORE the
-- testimonials table existed. Safe to run / re-run any time.
-- (If you run supabase-setup.sql fresh, this is already included.)
-- Supabase → SQL Editor → New query → paste → Run.
-- =====================================================================

-- 1) Table
create table if not exists public.testimonials (
  id         bigint generated by default as identity primary key,
  quote      text,
  name       text,
  location   text,
  photo_url  text,
  sort_order int default 0,
  published  boolean default true,
  created_at timestamptz default now()
);

-- 2) Row Level Security
alter table public.testimonials enable row level security;

-- 3) Public (visitors) can read published testimonies
drop policy if exists "Public can read testimonials" on public.testimonials;
create policy "Public can read testimonials"
  on public.testimonials for select using (published = true);

-- 4) Admins (see public.admins) can fully manage testimonies
drop policy if exists "admin manage testimonials" on public.testimonials;
create policy "admin manage testimonials" on public.testimonials for all to authenticated
  using      (exists (select 1 from public.admins a where a.email = auth.email()))
  with check (exists (select 1 from public.admins a where a.email = auth.email()));

-- 5) Seed a few starter testimonies (only if the table is empty)
insert into public.testimonials (quote, name, location, photo_url, sort_order)
select * from (values
  ('After years of waiting, God blessed my family with a child following the prophetic prayer. I am forever grateful to this ministry.','Grace A.','Lagos, Nigeria','https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=150&q=80',1),
  ('I was at the lowest point of my life when I joined a service online. The Word restored my hope and I found a new job within weeks.','Daniel O.','Abuja, Nigeria','https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=150&q=80',2),
  ('The medical outreach saved my mother''s life. This ministry truly cares for people beyond the pulpit. God bless Prophet Emmanuel.','Mary E.','Accra, Ghana','https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=150&q=80',3)
) as t
where not exists (select 1 from public.testimonials);
