-- =====================================================================
-- Dinab TV — ONE-SHOT Supabase setup (safe to run / re-run any time)
-- Creates ALL tables first, then security, then admin access.
-- Supabase → SQL Editor → New query → paste → Run.
-- =====================================================================

-- ========== 1. TABLES ==========
create table if not exists public.videos (
  id          bigint generated by default as identity primary key,
  title       text not null,
  section     text default 'Recent Messages',
  category    text,
  youtube_url text not null,
  description text,
  play_mode   text default 'inline',
  sort_order  int  default 0,
  published   boolean default true,
  created_at  timestamptz default now()
);
-- in case the table already existed without these:
alter table public.videos add column if not exists section   text default 'Recent Messages';
alter table public.videos add column if not exists play_mode text default 'inline';

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null, headline text, sort_order int default 0,
  published boolean default true, created_at timestamptz default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text, email text, subject text, message text, created_at timestamptz default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  name text, email text, phone text, amount numeric, status text, created_at timestamptz default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text, email text, phone text, country text, amount numeric, status text, created_at timestamptz default now()
);

create table if not exists public.admins (
  email text primary key, created_at timestamptz default now()
);

create table if not exists public.site_content (
  key text primary key, value text, updated_at timestamptz default now()
);

create table if not exists public.testimonials (
  id         bigint generated by default as identity primary key,
  quote      text,
  name       text,
  location   text,
  photo_url  text,
  sort_order int default 0,
  published  boolean default true,
  created_at timestamptz default now()
);

-- ========== 2. ENABLE ROW LEVEL SECURITY ==========
alter table public.videos       enable row level security;
alter table public.hero_slides  enable row level security;
alter table public.contacts     enable row level security;
alter table public.donations    enable row level security;
alter table public.partners     enable row level security;
alter table public.admins       enable row level security;
alter table public.site_content enable row level security;
alter table public.testimonials enable row level security;

-- ========== 3. PUBLIC (visitor) POLICIES ==========
drop policy if exists "Public can read published videos" on public.videos;
create policy "Public can read published videos" on public.videos for select using (published = true);

drop policy if exists "Public can read hero slides" on public.hero_slides;
create policy "Public can read hero slides" on public.hero_slides for select using (published = true);

drop policy if exists "Public can submit contact" on public.contacts;
create policy "Public can submit contact" on public.contacts for insert with check (true);

drop policy if exists "Public can submit donation" on public.donations;
create policy "Public can submit donation" on public.donations for insert with check (true);

drop policy if exists "Public can register partner" on public.partners;
create policy "Public can register partner" on public.partners for insert with check (true);

drop policy if exists "Public can read content" on public.site_content;
create policy "Public can read content" on public.site_content for select using (true);

drop policy if exists "Public can read testimonials" on public.testimonials;
create policy "Public can read testimonials" on public.testimonials for select using (published = true);

-- ========== 4. ADMIN ACCESS ==========
insert into public.admins (email) values ('admin@dinabtv.com') on conflict do nothing;

drop policy if exists "admins readable by authenticated" on public.admins;
create policy "admins readable by authenticated" on public.admins for select to authenticated using (true);

drop policy if exists "admin manage videos" on public.videos;
create policy "admin manage videos" on public.videos for all to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()))
  with check (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin manage hero" on public.hero_slides;
create policy "admin manage hero" on public.hero_slides for all to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()))
  with check (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin read contacts" on public.contacts;
create policy "admin read contacts" on public.contacts for select to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin read donations" on public.donations;
create policy "admin read donations" on public.donations for select to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin read partners" on public.partners;
create policy "admin read partners" on public.partners for select to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin manage content" on public.site_content;
create policy "admin manage content" on public.site_content for all to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()))
  with check (exists (select 1 from public.admins a where a.email = auth.email()));

drop policy if exists "admin manage testimonials" on public.testimonials;
create policy "admin manage testimonials" on public.testimonials for all to authenticated
  using (exists (select 1 from public.admins a where a.email = auth.email()))
  with check (exists (select 1 from public.admins a where a.email = auth.email()));

-- ========== 5. SEED VIDEOS (only if the table is empty) ==========
insert into public.videos (title, section, category, youtube_url, description, play_mode, sort_order)
select * from (values
  ('Live Service & Broadcasts','Watch Live','Live','https://www.youtube.com/watch?v=QM8jQHE5AAk','Join our services live from anywhere.','inline',0),
  ('Featured Broadcast','Featured','Latest','https://www.youtube.com/watch?v=rYJWRyg89wA','This week''s featured message.','inline',0),
  ('Distance Is Not A Barrier','Recent Messages','Prophetic Word','https://www.youtube.com/watch?v=rYJWRyg89wA','Distance is not a barrier — receive your breakthrough by faith.','inline',1),
  ('I Know Who I Am','Recent Messages','Identity in Christ','https://www.youtube.com/watch?v=frtZ4XfoXxM','Discover your true identity as a child of God.','inline',2),
  ('Way Maker — Worship','Praise & Worship','Worship','https://www.youtube.com/watch?v=hWgJij1MSI4','Enter His presence with powerful worship.','inline',3),
  ('TobeChukwu — Praise God','Praise & Worship','Thanksgiving','https://www.youtube.com/watch?v=0N8jWaBQUuA','Lift your voice in thanksgiving.','inline',4),
  ('Worship & Praise Medley','Crusades & Conferences','Worship Night','https://www.youtube.com/watch?v=eNKjlNyOFjY','An atmosphere of worship.','link',5)
) as v
where not exists (select 1 from public.videos);

-- ========== 6. SEED HERO IMAGES (only if empty) ==========
insert into public.hero_slides (image_url, sort_order)
select * from (values
  ('https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=1920&q=80',1),
  ('https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1920&q=80',2),
  ('https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1920&q=80',3)
) as h
where not exists (select 1 from public.hero_slides);

-- ========== 7. SEED TESTIMONIES (only if empty) ==========
insert into public.testimonials (quote, name, location, photo_url, sort_order)
select * from (values
  ('After years of waiting, God blessed my family with a child following the prophetic prayer. I am forever grateful to this ministry.','Grace A.','Lagos, Nigeria','https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=150&q=80',1),
  ('I was at the lowest point of my life when I joined a service online. The Word restored my hope and I found a new job within weeks.','Daniel O.','Abuja, Nigeria','https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=150&q=80',2),
  ('The medical outreach saved my mother''s life. This ministry truly cares for people beyond the pulpit. God bless Prophet Emmanuel.','Mary E.','Accra, Ghana','https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=150&q=80',3)
) as t
where not exists (select 1 from public.testimonials);

-- =====================================================================
-- DONE. Create the login if you haven't: Authentication → Users → Add user
--   admin@dinabtv.com / your password / ✅ Auto Confirm.
-- Then log in at /admin.html with username "admin".
-- =====================================================================
